// Barrel exports for easier imports
export { useAuth } from "./useAuth"
export { useClasses } from "./useClasses"
export { useSubjects } from "./useSubjects"
export { useTeachers } from "./useTeachers"
export { useTimeSlots } from "./useTimeSlots"
export { useTimetable } from "./useTimetable"
export { useTimetables } from "./useTimetables"
export { useTimetableSettings } from "./useTimetableSettings"
